
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 07 20:02:01 CST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROGRAMA = 2;
  public static final int LEE = 12;
  public static final int FINPROG = 3;
  public static final int VECES = 9;
  public static final int Comentario = 18;
  public static final int Numero = 14;
  public static final int ENTONCES = 5;
  public static final int IMPRIME = 11;
  public static final int ERROR = 15;
  public static final int Identificador = 13;
  public static final int Texto = 20;
  public static final int OperadorAritmetico = 17;
  public static final int OperadorRelacional = 16;
  public static final int EOF = 0;
  public static final int SINO = 6;
  public static final int SI = 4;
  public static final int error = 1;
  public static final int FINREP = 10;
  public static final int Asignacion = 19;
  public static final int REPITE = 8;
  public static final int FINSI = 7;
}

